urls:
  haus_und_grund:
    - "https://haus-und-grund-ostsee.de/luebeck/fuer-mieter/immobilien-mieten/#/list{}"
  sven_oldoerp:
    - "https://www.oldoerp-immobilien.de/mietangebotetest.html#filter=.geo-ort-luebeck"
  immowelt:
    - "https://www.immowelt.de/classified-search?distributionTypes=Rent&estateTypes=Apartment&locations=AD08DE3&numberOfRoomsMin=2&priceMax=1300&projectTypes=New_Build,Stock&spaceMin=50&page={}"
  immonet:
    - "https://www.immonet.de/classified-search?distributionTypes=Rent&estateTypes=Apartment&locations=AD08DE3&numberOfRoomsMin=2&priceMax=1000&spaceMin=50&order=DateDesc&page={}"

api-data:
  meine_stadt:
    - latitude: 53.8696
      longitude: 10.6876
      search_radius: 20
      max_price: 1200
      min_size: 40
      min_rooms: 2
