name: Build SvelteKit app

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: "Install PNPM"
        run: npm install -g pnpm
      - name: "Install dependencies"
        run: pnpm install
      - name: "Build app"
        run: npm run build --if-present

      - name: Upload built App
        uses: actions/upload-artifact@v4
        with:
          name: apartment-scraper-app
          path: build/
